# -*- coding: utf-8 -*-
"""CTDHACK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZsrJRVTSupzIWc2572RYYZBNpDt_QddC
"""

# Install required package
!pip install pdfplumber

import os
import sys
import json
from backend.extractor import extract_outline_from_pdf, extract_outlines_from_pdfs

def main():
    import argparse
    parser = argparse.ArgumentParser(description='Extract outline from PDF(s)')
    parser.add_argument('--input', required=True, help='Input PDF file or directory')
    parser.add_argument('--output', required=True, help='Output JSON file or directory')
    args = parser.parse_args()

    if os.path.isdir(args.input):
        pdf_files = [os.path.join(args.input, f) for f in os.listdir(args.input) if f.lower().endswith('.pdf')]
        os.makedirs(args.output, exist_ok=True)
        for pdf in pdf_files:
            outline = extract_outline_from_pdf(pdf)
            out_path = os.path.join(args.output, os.path.splitext(os.path.basename(pdf))[0] + '.json')
            with open(out_path, 'w', encoding='utf-8') as f:
                json.dump(outline, f, indent=2)
            print(f'Wrote {out_path}')
    else:
        outline = extract_outline_from_pdf(args.input)
        with open(args.output, 'w', encoding='utf-8') as f:
            json.dump(outline, f, indent=2)
        print(f'Wrote {args.output}')

if __name__ == '__main__':
    main()